!OPTIONS XOPT(NOEVAL)
PROGRAM MAIN_XXXX

!USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1  ,ONLY : JPIM     ,JPRB    ,JPRD
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMCST   , ONLY : TCST

!-----------------------------------------------------------------------

IMPLICIT NONE

!TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
!INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
!REAL(KIND=JPRB), POINTER, DIMENSION(:, :, :) :: ZZAPRS


!-----------------------------------------------------------------------

 
INTEGER(KIND=JPIM) :: JLEV, JLON

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-----------------------------------------------------------------------
INTEGER(KIND=JPIM) :: JLON, JBLK
INTEGER(KIND=JPIM) :: ILUNCI, ILUNFI, ILUNFO, IOUT
INTEGER(KIND=JPIM) :: NPROMA, NGPBLKS,KLEV,KLON,KGPBLKS
CHARACTER (LEN=128) :: CLOUT
CHARACTER (LEN=128) :: CLCASE_IN
CHARACTER (LEN=128) :: CLCASE_OUT
TYPE (DD12), POINTER :: YLD
LOGICAL :: LLVERBOSE, LLDIFF
INTEGER(KIND=JPIM), POINTER :: IBLOCKLIST (:)
!TYPE(STACK) :: YLSTACK
INTEGER(KIND=JPIM) :: ISIZE4, ISIZE8
CHARACTER*64 :: CLMETHOD
INTEGER(KIND=JPIM) :: ITIME, NTIME
LOGICAL :: LLSAVE, LLEXIST
REAL(KIND=JPRB) :: TSC, TEC, TSD, TED, ZTC, ZTD

IF (LHOOK) CALL DR_HOOK('MAIN_ACDRAG',0,ZHOOK_HANDLE)

YLD => NULL()

CALL INITOPTIONS

NPROMA  = 0; CALL GETOPTION("--nproma", NPROMA)
NGPBLKS = 0; CALL GETOPTION("--ngpblks", NGPBLKS)
CALL GET OPTION ("--case-in", CLCASE_IN, MND=.TRUE.)
CLCASE_OUT = ''; CALL GETOPTION ("--case-out", CLCASE_OUT)

CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--diff", LLDIFF)
#ifdef PARKIND1_SINGLE
ISIZE4 = 80;
ISIZE8 = 10;
#else
ISIZE4 = 10;
ISIZE8 = 80;
#endif
CALL GETOPTION ("--stack-size-4", ISIZE4)
CALL GETOPTION ("--stack-size-8", ISIZE8)
NTIME = 1; CALL GETOPTION ("--times", NTIME)

CLMETHOD = 'openmp'; CALL GETOPTION ("--method", CLMETHOD)

IBLOCKLIST => NULL ()
CALL GETOPTION ("--block-list", IBLOCKLIST)

LLSAVE = CLCASE_OUT /= ''

IF (LLSAVE) THEN
  CALL XRD_MKDIR (TRIM (CLCASE_OUT))
ENDIF

CLOUT = '-'; CALL GETOPTION ("--out", CLOUT)

CALL CHECKOPTIONS

CALL LOADALL

IF (LLVERBOSE) THEN
WRITE (0, *) " NPROMA = ", NPROMA, " NGPBLKS = ", NGPBLKS, " KLEV = ", KLEV
WRITE (0, *) " ISIZE4 = ", ISIZE4, " ISIZE8 = ", ISIZE8, " NTIME = ", NTIME
ENDIF

IF (LLSAVE) THEN
  CALL SAVEIALL
ENDIF


CALL GET_TIME (TSD)

CALL GET_TIME (TSC)

DO ITIME = 1, NTIME

  IF (TRIM (CLMETHOD) == 'openmp') THEN

!$OMP PARALLEL DO PRIVATE (JBLK)
    DO JBLK = 1, NGPBLKS
CALL CALLEE(...)
    ENDDO !jblk
  ENDIF !method omp/acc
ENDDO !time

CALL GET_TIME (TEC)
!IF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
!    CALL WIPE(...
!ENDIF
!!$ACC END DATA
CALL GET_TIME (TED)
ZTC = TEC - TSC
ZTD = TED - TSD

LLEXIST = .FALSE.

IF (CLOUT == '-') THEN
  IOUT = STDOUT
ELSE
  IOUT = 77
  INQUIRE (FILE=TRIM (CLOUT), EXIST=LLEXIST)
  IF (LLEXIST) THEN
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='OLD', POSITION='APPEND')
  ELSE
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='NEW')
  ENDIF
ENDIF

IF (.NOT. LLEXIST) &
WRITE (IOUT, '(A16,";",A32,";",A8,";",A8,";",A8,4(";",A20))') &
              & "CLARCH", "CLMETHOD", "NPROMA", "NGPBLKS", "NTIME", &
              & "ZTCTOT", "ZTC", "ZTDTOT", "ZTD"

WRITE (IOUT, '(A16,";",A32,";",I8,";",I8,";",I8,4(";",E20.10))') &
              & CLARCH,  TRIM (CLMETHOD), NPROMA, NGPBLKS, NTIME, &
              & ZTC, ZTC / REAL(NPROMA*NGPBLKS*NTIME, 8), &
              & ZTD, ZTD / REAL(NPROMA*NGPBLKS*NTIME, 8)

IF (IOUT /= STDOUT) THEN
  CLOSE (IOUT)
ENDIF


IF (LLDIFF) THEN
  CALL DIFFALL
ENDIF

IF (LLSAVE) THEN
  CALL SAVEOALL
ENDIF
WRITE (0, *) __FILE__, ':', __LINE__
IF (LHOOK) CALL DR_HOOK ('MAIN_ACDRAG', 1, ZHOOK_HANDLE)

CONTAINS

SUBROUTINE LOADALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_IN)//'/ACDRAG.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/ACDRAG.IN.dat',    FORM='UNFORMATTED')

!load derived types and scalars


!CALL ACDC_LOAD(ILUNCI, YDML_PHY_MF)
!CALL LOAD(ILUNCI, KLON)

KGPBLKS=IGPBLKS
IF (NPROMA == 0) NPROMA = KLON
IF (NGPBLKS == 0) THEN
  IF (ASSOCIATED (IBLOCKLIST)) THEN
    NGPBLKS = SIZE (IBLOCKLIST)
  ELSE
    NGPBLKS = KGPBLKS
  ENDIF
ENDIF

IF ((NPROMA /= KLON) .OR. (NGPBLKS /= KGPBLKS) .OR. ASSOCIATED (IBLOCKLIST)) THEN

  ALLOCATE (YLD)

  IF (ASSOCIATED (IBLOCKLIST)) THEN
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS], IBLOCKLIST)
  ELSE
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS])
  ENDIF

  NPROMA = YLD%IPROMA2
  NGPBLKS = YLD%IGPBLKS2

ENDIF

!load arrays
!CALL LOAD(ILUNFI, ZZAPRS, YDD=YLD)

CLOSE (ILUNFI)
CLOSE (ILUNCI)
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/ACDRAG.IN.dat',FORM='UNFORMATTED')
END SUBROUTINE

SUBROUTINE DIFFALL
IF (LLVERBOSE) PRINT *, " DIFF..."
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/ACDRAG.OUT.dat', FORM='UNFORMATTED')

!CALL DIFF('ZZSTRDU', ZZSTRDU, KLUN=ILUNFO, YDD=YLD)
CLOSE(ILUNFO)

IF (LLVERBOSE) PRINT *, " ...DIFF"

END SUBROUTINE


SUBROUTINE SAVEIALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_OUT)//'/ACDRAG.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_OUT)//'/ACDRAG.IN.dat',    FORM='UNFORMATTED')

!CALL ACDC_SAVE(YDML_PHY_MF, ILUNCI)
!CALL SAVE(KLON, ILUNCI)

!CALL SAVE(ZZAPRS, ILUNFI, KLBOUND=LBOUND(ZZAPRS))

CLOSE (ILUNFI)
CLOSE (ILUNCI)

END SUBROUTINE


SUBROUTINE SAVEOALL

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_OUT)//'/ACDRAG.OUT.dat', FORM='UNFORMATTED')

!CALL SAVE(ZZSTRDU, ILUNFO, KLBOUND=LBOUND(ZZSTRDU))
CLOSE (ILUNFO)
 
END SUBROUTINE

END PROGRAM MAIN_XXXX
