!OPTIONS XOPT(NOEVAL)
SUBROUTINE WRAP_XXXX ()

USE YOMXXXX !contains the buffers in which data is copied
USE YOMDATA !contains SAVE methods

! util_xxxxx_mod are generated by a scrip, see presentation
! example :
!fxtran-acdc/master/bin/fxtran-f90 --dryrun --method methods --methods save,load -- f90 -c model_physics_mf_type.F90
USE UTIL_XXXX_MOD !contains save methods for a derive type


USE PARKIND1  ,ONLY : JPIM     ,JPRB    ,JPRD

!-----------------------------------------------------------------------

IMPLICIT NONE

INTEGER :: ILUN
!-----------------------------------------------------------------------
ASSOCIATE(HOBST=>YDML_PHY_MF%YRPHY0%HOBST, GWDBC=>YDML_PHY_MF%YRPHY0%GWDBC, GWDCD=>YDML_PHY_MF%YRPHY0%GWDCD, &
 & GWDLT=>YDML_PHY_MF%YRPHY0%GWDLT, GWDVALI=>YDML_PHY_MF%YRPHY0%GWDVALI, GWDPROF=>YDML_PHY_MF%YRPHY0%GWDPROF, &
 & GWDAMP=>YDML_PHY_MF%YRPHY0%GWDAMP, GWDSE=>YDML_PHY_MF%YRPHY0%GWDSE, &
 & TSPHY=>YDML_PHY_MF%YRPHY2%TSPHY, &
 & RG=>YDCST%RG, RPI=>YDCST%RPI, &
 & NPHYREP=>YDML_PHY_MF%YRPHY%NPHYREP, LNEWD=>YDML_PHY_MF%YRPHY%LNEWD, LGLT=>YDML_PHY_MF%YRPHY%LGLT)

! 1) allocate data if not already allocated
IF (.NOT. LLALLOCATED) THEN

!$OMP CRITICAL

IF (.NOT. LLALLOCATED) THEN

  !ALLOCATE (PSTRDU_OUT(KLON, 0:KLEV, IGPBLKS))
  !======================
  !ALLOCATE (ZZAPRS(KLON, 0:KLEV, IGPBLKS))
  
  LLALLOCATED = .TRUE.
ENDIF 

!$OMP END CRITICAL

ENDIF

! 2) Copy input data 

IF (LLSAVE .AND. (JBLK == 1)) THEN
ILUN = 77
OPEN (ILUN, FILE='ACDRAG.CONST.dat', FORM='UNFORMATTED')

! For the first block, we save derived types and integers

!CALL ACDC_SAVE(YDCST, ILUN)
!CALL SAVE(KLON, ILUN)

CLOSE(ILUN)

ENDIF

! copy the data of the current block

!ZZAPRS(:, :, JBLK) = PAPRS(:, :)

! 3) call the routine
CALL CALLEE (...)

! 4) copy output data
!PSTRDU_OUT(:, :, JBLK) = PSTRDU(:, :)

END ASSOCIATE
END SUBROUTINE WRAP_XXXX
