MODULE UTIL_MODEL_PHYSICS_MF_TYPE_MOD

USE MODEL_PHYSICS_MF_MOD, ONLY : MODEL_PHYSICS_MF_TYPE

INTERFACE ACDC_SAVE
MODULE PROCEDURE ACDC_SAVE_MODEL_PHYSICS_MF_TYPE
END INTERFACE

INTERFACE ACDC_LOAD
MODULE PROCEDURE ACDC_LOAD_MODEL_PHYSICS_MF_TYPE
END INTERFACE







CONTAINS

SUBROUTINE ACDC_SAVE_MODEL_PHYSICS_MF_TYPE (SELF, KLUN)
USE UTIL_TPHY0_MOD
USE UTIL_TPHY2_MOD
USE UTIL_TPHY_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL ACDC_SAVE_TPHY (SELF%YRPHY, KLUN)
CALL ACDC_SAVE_TPHY0 (SELF%YRPHY0, KLUN)
CALL ACDC_SAVE_TPHY2 (SELF%YRPHY2, KLUN)
END SUBROUTINE

SUBROUTINE ACDC_LOAD_MODEL_PHYSICS_MF_TYPE (SELF, KLUN)
USE UTIL_TPHY0_MOD
USE UTIL_TPHY2_MOD
USE UTIL_TPHY_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (OUT), TARGET :: SELF
INTEGER, INTENT (IN) :: KLUN

CALL ACDC_LOAD_TPHY (SELF%YRPHY, KLUN)
CALL ACDC_LOAD_TPHY0 (SELF%YRPHY0, KLUN)
CALL ACDC_LOAD_TPHY2 (SELF%YRPHY2, KLUN)
END SUBROUTINE













END MODULE
