MODULE YOMACDRAG
!this modules contains the arrays in which the data is saved for all blocks

USE PARKIND1

IMPLICIT NONE

LOGICAL :: LLSAVE = .FALSE.

INTEGER :: IGPBLKS
INTEGER :: JBLK

!$OMP THREADPRIVATE (JBLK)

LOGICAL :: LLALLOCATED = .FALSE.

REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZAPRS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZAPRSF
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZDELP
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZNBVNO
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRDELP
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZU
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZV
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZRCORI
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZGETRL
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZGWDCS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZVRLAN
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :) :: ZZVRLDI
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZSTRDU
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZSTRDV
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: ZZRAPTRAJ
!======================
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PSTRDU_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PSTRDV_OUT
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:, :, :) :: PRAPTRAJ_OUT

END
